### ISSUE TITLE
run just commands within a container

### ISSUE THREAD

**Issue by scott-vsi** [VisionSystemsInc/vsi_common#104]
Following up on #94, I think it would be useful to be able to run `just` commands within a docker. This is conceptually the same thing as running `just` commands on the host without a docker. This might require splitting the entrypoint into two files: an entrypoint and a {service_name}.Justfile. (Although ALREADY_RUN_ONCE would be set, so that section would be skipped on subsequent run of the entrypoint.)

This way, I could run `just compile` or `just notebook` from within the container, which would run the compile or notebook subcommand of my entrypoint. I know I could run `/vsi/example_entrypoint.bsh compile`, or even alias `/vsi/example_entrypoint.bsh` to `just`, but that is not quite a nice. For example, that wouldn't provide some nice `just` features, like `help` and ability to call other subcommands via `justify`.

One downside, I can see there might be some confusion when running a `just` command and forgetting you are in the container, or visa-versa.

**Comment by scott-vsi** [comment]
In the **far** distant future, it would be cool if some of these internal subcommands (e.g., things like compile, clean, notebook, etc.) which have very straightforward entries in the Justfile, could be automatically lifted/exposed into the Justfile.

For example, my example service entrypoint, example_entrypoint.bsh, has a subcommand `compile`, which looks like this: 

```bash
case "${cmd}" in
   compile)
   # ...
   ;;
```

This subcommand is simply called by the Justfile like this:

```bash
example_compile) # run the compile subcommand of the example service
  Just-docker-compose run example compile
  ;;
```

If this could be auto-generated, it would reduce the amount of plumbing necessary to add subcommands to an entrypoint.

**Comment by scott-vsi** [comment]
NOTE @andyneff pointed out an existing alternative syntax in the Justfile:

```
## just dark magic
# example_compile) # run the compile subcommand of the example service
example_*) # run a subcommand of a service
  Just-docker-compose run ${just_arg#*_}
```

which is easier. Perhaps instead of exposing the subcommand directly, `just` could use its dark magic to simply expose its help message from example_entrypoint.bsh. That way, the documentation of the subcommand can be co-located with its implementation.

**Comment by andyneff** [comment]
*Thought*: Can the entire entrypoint be replaced by just, so all the logic that was in the entrypoint be summed up in a just plugin, and any of the current customization moved into the container Justfile?

**Comment by scott-vsi** [comment]
The main feature I'd like is the ability to call multiple subcommands in an entrypoint (example_entrypoint.Justfile or whatever). For example, I'd like to be able to run the `cmake-compile` subcommand before the `compile` subcommand.

Second, it would be nice to be able to see the help for the entrypoint so that I could see that I can run compile from within the container. Or kick off a complicated experiment, etc. 

@andyneff suggests we can modify the wildcard subcommand syntax from:

```
## just dark magic
# example_compile) # run the compile subcommand of the example service
# alternative_compile) # run the compile subcommand of the alternative servcie
example_*) # run a subcommand of a service
  Just-docker-compose run ${just_arg#*_}
```

(in this case, example is the service name as defined in the docker-compose.yml and compile is the subcommand in the entrypoint)

to use a plugin based architecture:

```
example_*) # run a subcommand of a service
  Just-docker-compose run ${just_arg}
```

You would then create a plugin with a `defaultify`, e.g., `example_defaultify` and some subcommands like `example_compile)`. 

```bash
function example_defaultify()
{
  arg=$1
  shift 1
  case $arg in
    example_compile) # compile
    # compile sources
    ;;
  *)
    (justify example_"${arg}")
    ;;
  esac
  return 0
}
```

In the host Justfile, you'd do this in order to add the subcommands to the help. 

```bash
JUST_HELP_FILES+=("docker/example_entrypoint.Justfile")
```

In the container the plugin would be a Justfile.

You would run `just example compile` on the host and in the container you can call either `just example compile` (which is exposed via the help) or a shortcut, `just compile`.

**Comment by decrispell** [comment]
It would be good if only a single file needed to be modified to add a new command.  If this is the way to accomplish that I'm for it.
