### ISSUE TITLE
Calling an environment modifying target from another target will not modify the target

### ISSUE THREAD

**Issue by andyneff** [VisionSystemsInc/vsi_common#105]
With or without #81, calling one target from another, never modifies the environment after calling. This could either be a feature or a burden.

Which should it be? @scott-vsi 

```
a)
  justify b
  echo ${FOO-}
  ;;
b)
  export FOO=bar
  ;;
```

This would not `echo bar`

**Comment by scott-vsi** [comment]
echo bar

**Comment by andyneff** [comment]
Ok. Let's call this a bug, and fix it. If the use want to have the subshell, they can add the `()`
