### ISSUE TITLE
Just winpty is in just environement

### ISSUE THREAD

**Issue by andyneff** [VisionSystemsInc/vsi_common#160]
On windows, when you run a just command, it acquires a TTY using `winpty` if you need one. This happens too late and the just environment is already loaded. At this point all of the `{PROJECT_NAME}_*` env variables are set, and so the "set if unset" doesn't override values when you change the .env file.

This will make changing env variables buggy, requiring you to restart your shell.

Have you observed this @drewgilliam ?

**Comment by drewgilliam** [comment]
I don't think I've seen this - I thought the winpty was permanently applied when you sourced the setup.env file, not when you ran a just command (maybe I'm using older just projects, and the setup.env is no longer necessary)?  

I tried on a just project - I successfully change variable values in the `{PROJECT_NAME}.env` file and the changes appear to be applied...

**Comment by andyneff** [comment]
When you run `just`/`juste`, it runs a tty check the first time, and caches the result in `JUST_IS_TTY` so that is is only ever checked once (speed reasons, also less likely to have a bug where you end up creating a `winpty` every time, that would be bad.) The problem was the environment was loaded before this check, so the winpty inherited all the exported variables. Since everything in `{proj}.env` only sets unset variables, since everything was set, they did not update correctly, as reproducible by these following steps:

1. `curl -LO https://raw.githubusercontent.com/VisionSystemsInc/vsi_common/master/linux/new_just`
1. bash ./new_just
1. `cd external/vsi_common`
1. `git checkout b2a144b36aa8653afda7b1673cbfc96541d43fac` # Today's master
1. `cd ../..`
1. edit `{proj}.env` and add `: ${BAR=15}`
1. `. setup.env`
1. `declare -p BAR` # Unset, not in winpty yet
1. `just --wrap declare -p BAR` # Now I'm in winpty
1. `declare -p BAR` # set!?
1. edit `{proj.env}` and change to 16
1. `just --wrap declare -p BAR` # Still 15 :(

At any rate, I've already fixed this. 👍
