### ISSUE TITLE
traps in tests on bash 3.2

### ISSUE THREAD

**Issue by scott-vsi** [VisionSystemsInc/vsi_common#282]
On macOS, Bash 3.2, if a test sets a EXIT trap with `trap_chain` (or calls a function that does so) and then dies, then when the signal is run, it resets the rv to 0 (assuming it runs successfully), causing the test not to die.

```bash
begin_test "Test trap"
(
  setup_test

  function _test_trap() { :; }
  trap_chain _test_trap EXIT
  echo "${unbound}"
)
end_test

# on macOS (bash 3.2)
# +testlib.bsh:604:end_test()	test_status=0
# trap - Test trap                       OK

# on centos 7 (bash 4.2)
# trap - Test trap                       FAILED
```

**Comment by andyneff** [comment]
Unfortunately, this is a limitation in bash 3.2 or older.

```
begin_test "Test trap"
(
  setup_test
  function _test_trap() {: }
  trap _test_trap EXIT
  echo "${unbound}"
)
end_test
```

- This simplified example, shows it has nothing to do with `trap_chain`, `just`, or `vsi_common` and is just an inherit behavior of bash 3.2 or older
- Unbound variable does not trigger trap `ERR`, but goes straight to `EXIT` so there is no way to handle it in `ERR`.
- `EXIT` traps like `_test_trap` cannot use `$?` to detect a non-zero return code, so there's no way to identify it there.
  - A complete dump of environment variables does not show anything useful either

There seems to be no way to cope with this short coming. a compat flag can be added for this behavior, but I honestly don't see what good knowing this shorting coming will do. 

This can definitely hide an unbound variable error in a unit test, if a prior function sets an EXIT trap, in bash 3.2
