### ISSUE TITLE
update_python_requirements rewrite

### ISSUE THREAD

**Issue by andyneff** [VisionSystemsInc/vsi_common#35]
update_python_requirements should be re-written and simplified to only run against one version of python, and shouldn't use array for filename name overrides.

It might also be nice to include a docker in vsi_common that is already setup and ready to go for update_python_requirements

**Comment by scott-vsi** [comment]
We've made such a docker before.

**Comment by scott-vsi** [comment]
There are a few features/design decisions that I think we should look at:

1. Can we remove the requirement that only source distributions are allowed? (unfortunately, @andyneff says no. Should find an example that fails.)
    - I understand this is to avoid installing packages, which can take a very long time if only a source distribution is available. But with manylinux and wheels, I think this problem is the exception. 
    - The requirement to use source distributions can artificially limit the versions that are available.
        - For example, torchvision only has version 0.1.6 available as source but version 0.2.0 available as binary.

1. I think that the requirements_python.txt and the requirements_python_custom.txt file should be combined and allow you to specify either a pinned version or a version range. E.g., pip supports version ranges: 0.1.*; 0.2,<0.3; etc [PEP-0440](https://www.python.org/dev/peps/pep-0440/#version-specifiers). This file should not be re-written each time update_python_requirements is run. The requirements_python_derived.txt file should continue to specify the exact version that is installed. 

1. update_python_requirements should error if an exception is thrown, e.g., if a package name is misspelled.

**Comment by scott-vsi** [comment]
Or use [pipenv](https://docs.pipenv.org/), which is now recommended by [python.org](https://packaging.python.org/tutorials/managing-dependencies/#managing-dependencies)

**Comment by andyneff** [comment]
Replaced with pipenv
