### ISSUE TITLE
add a setup step to `new_just`

### ISSUE THREAD

**Issue by scott-vsi** [VisionSystemsInc/vsi_common#39]
`new_just` should ask what you want your first app/service to be called. Currently there are the someappname and someappname2 placeholders which requires changing that name in the docker-compose.yml, Justfile, docker/base_someappname.Dockerfile, docker/someappname.Dockerfile, and docker/someappname_entrypoint.bsh.

**Comment by andyneff** [comment]
The intent for those files was to show you an example file. I suppose `example1` and `example2` would be better names than `someappname`

**Comment by scott-vsi** [comment]
Those would be better, but requires a lot of knowledge about just (and is tedious) to go into all those files and update them appropriately. I'd say asking the question with the default as example1 would be better.

**Comment by andyneff** [comment]
Completed in #42
