### ISSUE TITLE
error with new_just and docker_entrypoint

### ISSUE THREAD

**Issue by scott-vsi** [VisionSystemsInc/vsi_common#40]
linux/docker_entrypoint.bsh expects DOCKER_GROUP_NAMES to be defined, however, linux/new_just does not setup this variable in the .env file (it does set up GIDs).

**Comment by scott-vsi** [comment]
It looks like the issue is actually that DOCKER_GROUP_NAMES expects there to be at least 2 group names.

**Comment by andyneff** [comment]
The initial issue was fixed when working on #42

Just ran a test with:

```bash
: ${BLAH_GIDS=22}
: ${BLAH_GROUP_NAMES=two}
```

And there was no problem. Assuming problem fixed
