### ISSUE TITLE
Improve new_just

### ISSUE THREAD

**Issue by scott-vsi** [VisionSystemsInc/vsi_common#42]
- [x] #43 populate dockerignore
- [x] Fix `DOCKER_GROUP_NAMES` not being populated like GIDS
- [x] Add `git submodule update --init --recursive` to post `new_just` steps
- [x] #39 Input for app name, instead of "someappname"
- [ ] ~~Add arguments so all questions can be answered non-interactively~~
- [x] Change default dockerfile to use recipes for gosu and tini
    - [x] Add u+s permisision to gosu so non-privileged can run root
    - [x] Add `sudo` function?
    - [x] Add recipe build to just
- [x] #44 change entrypoint to not need execute permission. Left the old way in commented, in case someone wants to run an entrypoint with another interpreter. 
- [x] Make docker setup optional (but default yes), so I *could* make a simple just
- [x] Make default volumes use long format
- [x] Add pipenv
    - [x] Install pipenv
    - [x] Setup the default Pipfile/Pipfile.lock
    - [x] Setup the bootstrap virtual env and add commented volume to make it persistent
    - [x] Add example where gcc is needed, to install/uninstall
    - [ ] ~~Add example where python source is needed~~
    - [x] Fix `/venv` permission bug
    - [x] start in pipenv shell by default
    - [x] add pipenv run to entrypoint
    - [x] Pipfile.lock still isn't quiet bootstrapped to work well. Maybe add pipenv lock to entrypoint if PIpfile.lock is empty
- [x] Add new_just to README.md
- [x] Make project name host username specific (`docker_compose_sanitize_project_name`)
- [x] Add just sync

**Comment by andyneff** [comment]
All accepted tasks complete
