### ISSUE TITLE
new_just someappname_entrypoint.bsh

### ISSUE THREAD

**Issue by scott-vsi** [VisionSystemsInc/vsi_common#44]
In docker/base_someappname.Dockerfile, docker/someappname_entrypoint.bsh is added to the Dockerfile at /vsi and then chmod'd to 755. However, because these permissions don't match those of the file on the host, if you try to mount someappname_entrypoint.bsh over /vsi/someappname_entrypoint.bsh within the container (by adding it to <project>_VOLUMES), then you will get an error, "Cannot start service: OCI runtime create failed: container_linux.go.:348: start container process caused ... permission denied".

**Comment by andyneff** [comment]
~~It hard to rely on permissions when bind mounting, because when running on windows, all the rules changes. However, for the most part on windows *appears* to be executable.~~

Currently, new_just:

```dockerfile
ADD docker/someappname_entrypoint.bsh /
```

Not int `/vsi`, does that means this bug is already fixed?

**Comment by scott-vsi** [comment]
No. I think you need to chmod someappname_entrypoint.bsh on line [new_just#L441](https://github.com/VisionSystemsInc/vsi_common/blob/master/linux/new_just#L441)

**Comment by andyneff** [comment]
Why are you mounting in the entrypoint when it is already added to the image?

**Comment by scott-vsi** [comment]
For debugging. So that I don't have to rebuild the image every time I make a change.

**Comment by andyneff** [comment]
We'll try

```dockerfile
ENTRYPOINT ["/usr/bin/env", "bash", "/someappname_entrypoint.bsh"]
```

To see if that'll fix it.

**Comment by andyneff** [comment]
The default entrypoint itself also needs to be updates

```bash
ALREADY_RUN_ONCE=1 exec gosu ${DOCKER_USERNAME} bash $0 ${@+"${@}"}
```

**Comment by andyneff** [comment]
Completed and tested. Entrypoint works without execute permissions now, as long as it is a bash script. The down side is you need to hard code the shebang line in the Dockerfile/entrypoint, but it does get around the execute permissions issue
