### ISSUE TITLE
pipenv install --keep-outdated {package} doesn't work

### ISSUE THREAD

**Issue by scott-vsi** [VisionSystemsInc/vsi_common#82]
`pipenv install --keep-outdated {package}` doesn't actually work. When processing the {package}, pipenv (irritatingly) goes ahead and updates the packages in the Pipfile.lock. Basically, `pipenv install --keep-outdated` should not be used with the {package} arg, it should be considered a synonym for `pipenv sync`.

**Comment by andyneff** [comment]
Fixed by never using this syntax, now `pip` is used to preload modules like `numpy`
